### PR TITLE
fix: payload limiter gauge reports invalid value type

### LINKED ISSUE #3046: The latest version has a lot of error logs about adaptive_payload_limiter
**Describe the bug**
The latest version has a lot of error logs about adaptive_payload_limiter

```[inputs.statsd] Error: parsing value to float64: adaptive_payload_limiter_state,instanceName=rudderstack-1,namespace=rudderstack:|g```
image

**Steps to reproduce the bug**
Enter the steps to reproduce the behavior. 

For e.g:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Any additional context**
Add any other context that will help us understand the problem better.

### PR DESCRIPTION
**Pull request by Sidddddarth**
# Description

Using proper numeric values (non-custom types) for limiter stats. Fixes #3046

## Notion Ticket

[ref github issue](https://github.com/rudderlabs/rudder-server/issues/3046)

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

File: utils/payload/limiter_setup.go [hunk 1]
```diff
@@ -54,14 +54,25 @@ func SetupAdaptiveLimiter(ctx context.Context, g *errgroup.Group) AdaptiveLimite
 			case <-time.After(statsFrequency):
 				limiterStats := limiter.Stats()
 
-				stats.Default.NewStat("adaptive_payload_limiter_state", stats.GaugeType).Gauge(limiterStats.State)
-				stats.Default.NewStat("adaptive_payload_limiter_threshold_factor", stats.GaugeType).Gauge(limiterStats.ThresholdFactor)
+				stats.Default.NewStat(
+					"adaptive_payload_limiter_state",
+					stats.GaugeType,
+				).Gauge(float64(limiterStats.State))
```
Comment (atzoum) [inline utils/payload/limiter_setup.go:60]: why do we need to cast? Are we really casting everywhere else we are using gauges?

Comment (Sidddddarth) [reply utils/payload/limiter_setup.go:60]: we're not yeah🤡 
understood

Comment (atzoum) [inline utils/payload/limiter_setup.go:60]: The underlying type is an `int` really
```suggestion
				).Gauge(int(limiterStats.State))
```

**Review by atzoum — APPROVED** [review]
